server {
    listen 80;
    server_name einvoices.telegroup.lv;

    location ~ ^/.well-known/acme-challenge/ {
        root /acme-challenge;
    }

    location = /.well-known/acme-challenge/ {
        return 404;
    }

    location / {
        return 301 https://$server_name$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name einvoices.telegroup.lv;

    ssl_certificate /acme-certificates/fullchain.cer;
    ssl_certificate_key /acme-certificates/einvoices.telegroup.lv.key;

    location / {
        proxy_set_header X-Forwarded-Host $host;
        proxy_pass http://erekini-nextjs:3000;
    }
}