name: minicrm
services:
  minicrm-acme:
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile.acme
    image: minicrm-acme
    container_name: minicrm-acme
    tty: true
    restart: always
    volumes:
      - /app/acme-challenge:/acme-challenge
      - /app/acme-certificates:/acme.sh/minicrm.local
      - /var/run/docker.sock:/var/run/docker.sock
  minicrm-nginx:
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile.nginx
    image: minicrm-nginx
    container_name: minicrm-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /app/acme-challenge:/acme-challenge
      - /app/acme-certificates:/acme-certificates
  minicrm-nextjs:
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile.nextjs
    image: minicrm-nextjs
    container_name: minicrm-nextjs
    restart: always
    ports:
      - "3000:3000"
  minicrm-postgres:
    image: postgres:16-alpine
    container_name: minicrm-postgres
    env_file: ../../.env.prod.local
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /app/postgres:/var/lib/postgresql/data
