# Required in Alpine. See link
# https://github.com/nodejs/docker-node/tree/89b29ef06b421598ec007605a2604ede0348b298?tab=readme-ov-file#nodealpine
FROM node:24-alpine AS base-image
RUN apk add --no-cache gcompat

FROM base-image AS dependencies-image
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm i

FROM base-image AS build-image
# Required for Prisma to work with Alpine
# RUN apk add --no-cache openssl
WORKDIR /app
COPY --from=dependencies-image /app/node_modules ./node_modules
COPY . .
COPY .env.prod.local .env.production
RUN npm run build

FROM base-image AS final-image
# Required for Prisma to work with Alpine
# RUN apk add --no-cache openssl
WORKDIR /app

COPY --from=build-image /app/public ./public
COPY --from=build-image /app/.next/standalone ./
COPY --from=build-image /app/.next/static ./.next/static
COPY --from=build-image /app/node_modules ./node_modules
COPY --from=build-image /app/prisma ./prisma
COPY --from=build-image /app/docker/prod/entrypoint.nextjs.sh ./
RUN chmod +x entrypoint.nextjs.sh

ENV NODE_ENV=production
ENV PORT=3000

CMD ["./entrypoint.nextjs.sh"]
